# Generated by Django 2.1 on 2021-02-02 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(related_name='article_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
